build:
  maxIssues: 0
  excludeCorrectable: false
  weights:
    # complexity: 2
    # LongParameterList: 1
    # style: 1
    # comments: 1

style:
  MagicNumber:
    active: true
    ignoreNumbers: ['-1', '0', '1', '2']
  MaxLineLength:
    active: true
    maxLineLength: 120

complexity:
  TooManyFunctions:
    active: true
    thresholdInFiles: 20
  LongParameterList:
    active: true
    functionThreshold: 10
    constructorThreshold: 15
